title: Xintian Stella Li # your name (or website title) here
logo: "/images/resume2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, My name is Xintian Stella Li. I am a graduate student at Upenn, pursuing a dual degree in Urban Planning and Urban Spatial Analytics. I am expected to graduate in December 2021.
  <br><br>
  I am a transportation planner who is enthusiastic about solving urban problems with data-dirven methods. Also have a background in urban design and urban planning.  
  <br><br>
  <a href="https://www.linkedin.com/in/xintian-stella-li/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 
# your Google Analytics tracking ID here
