title: Stella(Xintian) Li # your name (or website title) here
logo: "/images/resume2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  University of Pennsylvania
  <br>
  Dual degree candidate (Expected to graudate in December 2021)
  <br>
  Master of Urban Spatial analytics
  <br>
  Master of Urban Planning
  # <br>
  # Hi, My name is Stella(Xintian) Li. I am a graduate student at Upenn, pursuing a dual degree in Urban Spatial Analytics and Urban Planning. I am expected to graduate in December 2021.
  <br><br>
  I am a GIS analyst using spatial data analytics and data visualization to model spatial and temporal trends and identify spatial patterns. I am also an urban enthusiastic interested in solving urban problems with data-dirven methods, specifically around multimodal transporation planning .  
  <br><br>
  <a href="https://www.linkedin.com/in/xintian-stella-li/">LinkedIn Profile</a> 
  <a href="https://www.linkedin.com/in/xintian-stella-li/">Resume</a>
  
# theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 
# your Google Analytics tracking ID here
