title: Stella(Xintian) Li # your name (or website title) here
logo: "/images/resume2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  University of Pennsylvania
  <br>
  Dual degree candidate
  <br>
  Master of Urban Spatial Analytics
  <br>
  Master of Urban Planning
  <br><br>
  GIS analyst using spatial data analytics and data visualization to model spatial and temporal trends and identify spatial patterns. Urban enthusiast interested in solving urban problems with data-dirven methods, specifically around multimodal transporation planning.  
  <br><br>
  <a href="https://www.linkedin.com/in/xintian-stella-li/">LinkedIn Profile</a> 
  <br><br>
  <a href="https://drive.google.com/file/d/1QeOAa_JZMJbDdaPxW69FrqgixoDW7bQ6/view?usp=sharing">Resume</a>
 
 
 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 
# your Google Analytics tracking ID here
