title: Xintian Stella Li # your name (or website title) here
logo: "/images/resume2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, My Name is Xintian Stella Li. I am a master student at Upenn, pursuing a dual degree in Urban Planning and Urban Spatial Analytics. 
  <br><br>
  I am enthusiastic about solving urban problems with data-dirven methods and I also have a background of urban design and urban planning. Please feel free to contact me if you have any question about my work samples or my background! 
  <br><br>
  <a href="https://www.linkedin.com/in/xintian-stella-li/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 
# your Google Analytics tracking ID here
